//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayshiftTranslateFGO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayshiftTranslateFGO.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork credit: 冬木 @.
        /// </summary>
        internal static string AboutArtworkCredit {
            get {
                return ResourceManager.GetString("AboutArtworkCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string AboutChangeLanguage {
            get {
                return ResourceManager.GetString("AboutChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app allows you to access various story translations for.
        /// </summary>
        internal static string AboutFlavourText {
            get {
                return ResourceManager.GetString("AboutFlavourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesystem Access Mode.
        /// </summary>
        internal static string AboutFSPreferenceButton {
            get {
                return ResourceManager.GetString("AboutFSPreferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string AboutLearnMore {
            get {
                return ResourceManager.GetString("AboutLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfigure Android 11+ Setup.
        /// </summary>
        internal static string AboutRetrySetup {
            get {
                return ResourceManager.GetString("AboutRetrySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string AboutTitle1 {
            get {
                return ResourceManager.GetString("AboutTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string AboutTitle2 {
            get {
                return ResourceManager.GetString("AboutTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string AboutTitle3 {
            get {
                return ResourceManager.GetString("AboutTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit rayshift.io for more information..
        /// </summary>
        internal static string AboutVisitText {
            get {
                return ResourceManager.GetString("AboutVisitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter pre-release key.
        /// </summary>
        internal static string AddPreReleaseKey {
            get {
                return ResourceManager.GetString("AddPreReleaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device requires you to set up special access to write to Fate/Grand Order&apos;s files. Please click Yes to set this up now..
        /// </summary>
        internal static string Android11AskToSetup {
            get {
                return ResourceManager.GetString("Android11AskToSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further setup required for Android 11+.
        /// </summary>
        internal static string Android11Setup {
            get {
                return ResourceManager.GetString("Android11Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must grant this app permission to write to the directories where Fate/Grand Order stores cached data..
        /// </summary>
        internal static string Android11Setup0 {
            get {
                return ResourceManager.GetString("Android11Setup0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap each button below, then tap &quot;Use this folder&quot;..
        /// </summary>
        internal static string Android11Setup1 {
            get {
                return ResourceManager.GetString("Android11Setup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return here with &quot;About -&gt; Reconfigure Android 11+ Setup&quot; if you install a new version of the game..
        /// </summary>
        internal static string Android11Setup2 {
            get {
                return ResourceManager.GetString("Android11Setup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Android11SetupSuccessful {
            get {
                return ResourceManager.GetString("Android11SetupSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m on Android 12/13.
        /// </summary>
        internal static string Android1213 {
            get {
                return ResourceManager.GetString("Android1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data folder is empty or inaccessible. Ensure you have launched FGO at least once..
        /// </summary>
        internal static string AndroidDataFolderEmpty {
            get {
                return ResourceManager.GetString("AndroidDataFolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder was not &quot;Android&quot;, instead found &quot;{0}&quot;, please try again..
        /// </summary>
        internal static string AndroidFolderNotSelected {
            get {
                return ResourceManager.GetString("AndroidFolderNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art to Install: .
        /// </summary>
        internal static string ArtCount {
            get {
                return ResourceManager.GetString("ArtCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to install custom art to your game.
        ///Ensure you have made and written down your bind code before using this application.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string ArtInstallWarning {
            get {
                return ResourceManager.GetString("ArtInstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} starred, {2}/{3} total.
        /// </summary>
        internal static string ArtStatus {
            get {
                return ResourceManager.GetString("ArtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starred, {1} total.
        /// </summary>
        internal static string ArtTotalSize {
            get {
                return ResourceManager.GetString("ArtTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string ArtUninstallingButton {
            get {
                return ResourceManager.GetString("ArtUninstallingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your asset database may be corrupted. Please try opening and closing Fate/Grand Order to fix the problem..
        /// </summary>
        internal static string AssetWarningCorrupted {
            get {
                return ResourceManager.GetString("AssetWarningCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your asset database version is up to date, but the story scripts have not been released yet. Please try again later, or report this as a bug..
        /// </summary>
        internal static string AssetWarningFutureUnreleased {
            get {
                return ResourceManager.GetString("AssetWarningFutureUnreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game does not have the newest assets. Please open Fate/Grand Order and download the data update before installing story scripts..
        /// </summary>
        internal static string AssetWarningOutOfDate {
            get {
                return ResourceManager.GetString("AssetWarningOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your asset database version was not recognised. Story scripts may not work properly. Please try again later, or report this as a bug..
        /// </summary>
        internal static string AssetWarningUnrecognised {
            get {
                return ResourceManager.GetString("AssetWarningUnrecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for donors.
        /// </summary>
        internal static string AvailableToDonors {
            get {
                return ResourceManager.GetString("AvailableToDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this device you must locate the following folder: {0}.
        ///
        ///Ensure &quot;Show internal storage&quot; (top right menu on BlueStacks) is selected if you cannot find it.
        ///
        ///Once you see the folders &quot;cache&quot; and &quot;files&quot;, tap &quot;Use this folder&quot;..
        /// </summary>
        internal static string BluestacksWarning {
            get {
                return ResourceManager.GetString("BluestacksWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed. Your phone likely has a poor connection to the internet, try again later..
        /// </summary>
        internal static string ChunkUploadFailed {
            get {
                return ResourceManager.GetString("ChunkUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Account.
        /// </summary>
        internal static string ConnectAccount {
            get {
                return ResourceManager.GetString("ConnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI translation (English only) and custom art are only available for donors.
        ///
        ///Connect your Rayshift account now?.
        /// </summary>
        internal static string ConnectAccountInfo {
            get {
                return ResourceManager.GetString("ConnectAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI translation (English only) and custom art are only available for donors.
        ///
        ///If you have already donated, connect your account in your profile settings..
        /// </summary>
        internal static string ConnectAccountNotDonatedInfo {
            get {
                return ResourceManager.GetString("ConnectAccountNotDonatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string CustomArtTab {
            get {
                return ResourceManager.GetString("CustomArtTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate FGO requires write access to your storage to operate. Please allow this access when requested..
        /// </summary>
        internal static string DirectoryPermissionAccessBody {
            get {
                return ResourceManager.GetString("DirectoryPermissionAccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage access required.
        /// </summary>
        internal static string DirectoryPermissionAccessTitle {
            get {
                return ResourceManager.GetString("DirectoryPermissionAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application was unable to get write access to your storage. If this persists, try re-installing the app, otherwise please report it as a bug. Retry?.
        /// </summary>
        internal static string DirectoryPermissionDeniedBody {
            get {
                return ResourceManager.GetString("DirectoryPermissionDeniedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DirectoryPermissionDeniedTitle {
            get {
                return ResourceManager.GetString("DirectoryPermissionDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string DonateButton {
            get {
                return ResourceManager.GetString("DonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string DonorPrompt {
            get {
                return ResourceManager.GetString("DonorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto script update.
        /// </summary>
        internal static string EnableAutoScriptUpdate {
            get {
                return ResourceManager.GetString("EnableAutoScriptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter authentication key.
        /// </summary>
        internal static string EnterAuthKey {
            get {
                return ResourceManager.GetString("EnterAuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to clear the current authentication key?.
        /// </summary>
        internal static string EnterAuthKeyClear {
            get {
                return ResourceManager.GetString("EnterAuthKeyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an authentication key to access content under development, enter it here..
        /// </summary>
        internal static string EnterAuthKeyDescription {
            get {
                return ResourceManager.GetString("EnterAuthKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the key is invalid..
        /// </summary>
        internal static string EnterAuthKeyInvalid {
            get {
                return ResourceManager.GetString("EnterAuthKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder was not a valid FGO installation, instead found &quot;{0}&quot;, please try again..
        /// </summary>
        internal static string FGOFolderNotSelected {
            get {
                return ResourceManager.GetString("FGOFolderNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game never launched, or wrong folder selected..
        /// </summary>
        internal static string FGOWrongGameSelected {
            get {
                return ResourceManager.GetString("FGOWrongGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install All.
        /// </summary>
        internal static string InstallAll {
            get {
                return ResourceManager.GetString("InstallAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Asset database update for {0} failed, error code {1}.
        ///Error message: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallAssetStorageAPIFailure {
            get {
                return ResourceManager.GetString("InstallAssetStorageAPIFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Checksum failure on {0}. Real file length: {1} 
        ///Download URL: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallChecksumFailure {
            get {
                return ResourceManager.GetString("InstallChecksumFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading art {0} of {1}....
        /// </summary>
        internal static string InstallDownloadingArts {
            get {
                return ResourceManager.GetString("InstallDownloadingArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading script {0} of {1}....
        /// </summary>
        internal static string InstallDownloadingScripts {
            get {
                return ResourceManager.GetString("InstallDownloadingScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating asset databases....
        /// </summary>
        internal static string InstallDownloadNewAssetStorage {
            get {
                return ResourceManager.GetString("InstallDownloadNewAssetStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string InstalledText {
            get {
                return ResourceManager.GetString("InstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Asset database update for {0} failed, path {1} inaccessible or empty.
        ///Error: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallEmptyAssetStorage {
            get {
                return ResourceManager.GetString("InstallEmptyAssetStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Extra file update for {0} failed, path {1} inaccessible or empty.
        ///Error: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallEmptyExtraFile {
            get {
                return ResourceManager.GetString("InstallEmptyExtraFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Script {0} returned empty. URL: {1}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallEmptyFileFailure {
            get {
                return ResourceManager.GetString("InstallEmptyFileFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Installer.
        /// </summary>
        internal static string InstallerTitle {
            get {
                return ResourceManager.GetString("InstallerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Extra file update for {0} failed, error code {1}.
        ///Error message: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallExtraAPIFailure {
            get {
                return ResourceManager.GetString("InstallExtraAPIFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing extra files - stage {0}/{1} {2}%.
        /// </summary>
        internal static string InstallExtraFiles {
            get {
                return ResourceManager.GetString("InstallExtraFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished!.
        /// </summary>
        internal static string InstallFinished {
            get {
                return ResourceManager.GetString("InstallFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script.
        ///
        ///Remote server unavailable, try again later. Error: {0}
        ///Message: {1}.
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallHandshakeFailure {
            get {
                return ResourceManager.GetString("InstallHandshakeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This script is not currently available for install..
        /// </summary>
        internal static string InstallHiddenScriptFailure {
            get {
                return ResourceManager.GetString("InstallHiddenScriptFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initializing....
        /// </summary>
        internal static string InstallingFetchingHandshake {
            get {
                return ResourceManager.GetString("InstallingFetchingHandshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install the UI translation, as you are missing the files required. Please open all versions of Fate/Grand Order to the login screen, close them, and then try again..
        /// </summary>
        internal static string InstallMissingExtraFile {
            get {
                return ResourceManager.GetString("InstallMissingExtraFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script.
        ///
        ///Script {0} not available..
        /// </summary>
        internal static string InstallMissingScriptFailure {
            get {
                return ResourceManager.GetString("InstallMissingScriptFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing a script. 
        ///
        ///Download for {0} returned failure. URL: {1}
        ///Message: {2}
        ///
        ///Please try again later, or report as a bug if the issue persists..
        /// </summary>
        internal static string InstallScriptDownloadFailure {
            get {
                return ResourceManager.GetString("InstallScriptDownloadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Starred.
        /// </summary>
        internal static string InstallStarred {
            get {
                return ResourceManager.GetString("InstallStarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallText {
            get {
                return ResourceManager.GetString("InstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to install a set of scripts to your game.
        ///Ensure you have made and written down your bind code before using this application.
        ///
        ///Total download size: {0}
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string InstallWarning {
            get {
                return ResourceManager.GetString("InstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing file {0} of {1}....
        /// </summary>
        internal static string InstallWriteFile {
            get {
                return ResourceManager.GetString("InstallWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred, please report this as a bug.
        ///
        ///{0}.
        /// </summary>
        internal static string InternalErrorDetails {
            get {
                return ResourceManager.GetString("InternalErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Art (JP).
        /// </summary>
        internal static string JPArtName {
            get {
                return ResourceManager.GetString("JPArtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FGO JP.
        /// </summary>
        internal static string JPInstaller {
            get {
                return ResourceManager.GetString("JPInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated: .
        /// </summary>
        internal static string LastUpdatedText {
            get {
                return ResourceManager.GetString("LastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Rayshift Account.
        /// </summary>
        internal static string LinkAccount {
            get {
                return ResourceManager.GetString("LinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to link account, reason: {0}.
        /// </summary>
        internal static string LinkAccountFailure {
            get {
                return ResourceManager.GetString("LinkAccountFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Rayshift account {0}.
        /// </summary>
        internal static string LinkAccountSuccess {
            get {
                return ResourceManager.GetString("LinkAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        internal static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Rayshift Account.
        /// </summary>
        internal static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Art (NA).
        /// </summary>
        internal static string NAArtName {
            get {
                return ResourceManager.GetString("NAArtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FGO NA.
        /// </summary>
        internal static string NAInstaller {
            get {
                return ResourceManager.GetString("NAInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found on your system. Please install the game and ensure you have run it at least once.
        ///
        ///If you believe this is an error, try the &quot;Android 11 Setup&quot; in the about tab first. (error 1).
        /// </summary>
        internal static string NoFGOFound {
            get {
                return ResourceManager.GetString("NoFGOFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found on your system. Please install the game and ensure you have run it at least once.
        ///
        ///If you believe this is an error, try the &quot;Android 11 Setup&quot; in the about tab first. (error 2).
        /// </summary>
        internal static string NoFGOInstallationFound2 {
            get {
                return ResourceManager.GetString("NoFGOInstallationFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fate/GO installation was found in this location. Please ensure you have launched Fate/GO at least once..
        /// </summary>
        internal static string NoFGOInstallationFoundToast {
            get {
                return ResourceManager.GetString("NoFGOInstallationFoundToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translation scripts are currently available for download. Please try again later..
        /// </summary>
        internal static string NoScriptsAvailable {
            get {
                return ResourceManager.GetString("NoScriptsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        internal static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable auto script update.
        /// </summary>
        internal static string RemoveAutoScriptUpdate {
            get {
                return ResourceManager.GetString("RemoveAutoScriptUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove pre-release key.
        /// </summary>
        internal static string RemovePreReleaseKey {
            get {
                return ResourceManager.GetString("RemovePreReleaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen Announcement.
        /// </summary>
        internal static string ReopenAnnouncement {
            get {
                return ResourceManager.GetString("ReopenAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset application.
        /// </summary>
        internal static string ResetApp {
            get {
                return ResourceManager.GetString("ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the application?.
        /// </summary>
        internal static string ResetAppText {
            get {
                return ResourceManager.GetString("ResetAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart your phone to use TranslateFGO!.
        /// </summary>
        internal static string RestartNeededBody {
            get {
                return ResourceManager.GetString("RestartNeededBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use the old patching method instead? On Android 12+, this may require Shizuku..
        /// </summary>
        internal static string RestartNeededDialog2 {
            get {
                return ResourceManager.GetString("RestartNeededDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That didn&apos;t help.
        /// </summary>
        internal static string RestartNeededHelp {
            get {
                return ResourceManager.GetString("RestartNeededHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Restart Required.
        /// </summary>
        internal static string RestartNeededTitle {
            get {
                return ResourceManager.GetString("RestartNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string RetryText {
            get {
                return ResourceManager.GetString("RetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which filesystem access mode to use.
        /// </summary>
        internal static string SetFSPreferenceBody {
            get {
                return ResourceManager.GetString("SetFSPreferenceBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string SetupButton {
            get {
                return ResourceManager.GetString("SetupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setup failed or was cancelled. Failure point: .
        /// </summary>
        internal static string SetupFailedBody {
            get {
                return ResourceManager.GetString("SetupFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Failed.
        /// </summary>
        internal static string SetupFailedTitle {
            get {
                return ResourceManager.GetString("SetupFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you get the error &quot;To protect your privacy, choose another folder&quot;, tap &quot;Use Shizuku Instead&quot;..
        /// </summary>
        internal static string ShizukuAndroid11Notice {
            get {
                return ResourceManager.GetString("ShizukuAndroid11Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Tutorial.
        /// </summary>
        internal static string ShizukuButtonVideo {
            get {
                return ResourceManager.GetString("ShizukuButtonVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Shizuku Connection.
        /// </summary>
        internal static string ShizukuConnect {
            get {
                return ResourceManager.GetString("ShizukuConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shizuku isn&apos;t running. Ensure Shizuku is started..
        /// </summary>
        internal static string ShizukuConnectFailure {
            get {
                return ResourceManager.GetString("ShizukuConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Shizuku.
        /// </summary>
        internal static string ShizukuDownload {
            get {
                return ResourceManager.GetString("ShizukuDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Shizuku....
        /// </summary>
        internal static string ShizukuLoading {
            get {
                return ResourceManager.GetString("ShizukuLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shizuku isn&apos;t installed on your device, or it isn&apos;t active. Please follow the tutorial video if you&apos;re stuck..
        /// </summary>
        internal static string ShizukuNotInstalled {
            get {
                return ResourceManager.GetString("ShizukuNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shizuku service disconnected. You may need to restart this app..
        /// </summary>
        internal static string ShizukuServiceLost {
            get {
                return ResourceManager.GetString("ShizukuServiceLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you get the error &quot;To protect your privacy, choose another folder&quot;, you must install Shizuku first..
        /// </summary>
        internal static string ShizukuSetup1 {
            get {
                return ResourceManager.GetString("ShizukuSetup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the tutorial video below if you have never used Shizuku before. It explains what Shizuku is and how to install it..
        /// </summary>
        internal static string ShizukuSetup2 {
            get {
                return ResourceManager.GetString("ShizukuSetup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to start Shizuku every time your device restarts in order to use TranslateFGO..
        /// </summary>
        internal static string ShizukuSetup3 {
            get {
                return ResourceManager.GetString("ShizukuSetup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap &quot;Check Shizuku Connection&quot; when it is installed and active..
        /// </summary>
        internal static string ShizukuSetup4 {
            get {
                return ResourceManager.GetString("ShizukuSetup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shizuku Setup.
        /// </summary>
        internal static string ShizukuSetupTitle {
            get {
                return ResourceManager.GetString("ShizukuSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android 8.0+ Required.
        /// </summary>
        internal static string ShizukuTooLowAndroidVersion {
            get {
                return ResourceManager.GetString("ShizukuTooLowAndroidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Shizuku Instead.
        /// </summary>
        internal static string ShizukuUseInstead {
            get {
                return ResourceManager.GetString("ShizukuUseInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error, try reinstalling.
        /// </summary>
        internal static string StatusErrorTryReinstall {
            get {
                return ResourceManager.GetString("StatusErrorTryReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed.
        /// </summary>
        internal static string StatusInstalled {
            get {
                return ResourceManager.GetString("StatusInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update required, launch game and download update first.
        /// </summary>
        internal static string StatusMismatch {
            get {
                return ResourceManager.GetString("StatusMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not installed.
        /// </summary>
        internal static string StatusNotInstalled {
            get {
                return ResourceManager.GetString("StatusNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        internal static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown state, try reinstalling.
        /// </summary>
        internal static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update available.
        /// </summary>
        internal static string StatusUpdateAvailable {
            get {
                return ResourceManager.GetString("StatusUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update required.
        /// </summary>
        internal static string StatusUpdateRequired {
            get {
                return ResourceManager.GetString("StatusUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string TimeAgo {
            get {
                return ResourceManager.GetString("TimeAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android 7.0+ required.
        /// </summary>
        internal static string TooLowAndroidVersion {
            get {
                return ResourceManager.GetString("TooLowAndroidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Size: .
        /// </summary>
        internal static string TotalSize {
            get {
                return ResourceManager.GetString("TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations are currently unavailable..
        /// </summary>
        internal static string TranslateAPIError {
            get {
                return ResourceManager.GetString("TranslateAPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Translation API is currently down, please try again later..
        /// </summary>
        internal static string TryAgainLater {
            get {
                return ResourceManager.GetString("TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to uninstall any artwork currently installed.
        ///Ensure you have made and written down your bind code before using this application.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string UninstallArtWarning {
            get {
                return ResourceManager.GetString("UninstallArtWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        internal static string UninstallFinished {
            get {
                return ResourceManager.GetString("UninstallFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0}/{1}....
        /// </summary>
        internal static string UninstallingText {
            get {
                return ResourceManager.GetString("UninstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UninstallText {
            get {
                return ResourceManager.GetString("UninstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to uninstall any translated scripts currently installed.
        ///Ensure you have made and written down your bind code before using this application.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string UninstallWarning {
            get {
                return ResourceManager.GetString("UninstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred. {0}.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Rayshift Account.
        /// </summary>
        internal static string UnlinkAccount {
            get {
                return ResourceManager.GetString("UnlinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlink your account?.
        /// </summary>
        internal static string UnlinkConfirmation {
            get {
                return ResourceManager.GetString("UnlinkConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An optional update is available for TranslateFGO. Do you want to download and install it?.
        /// </summary>
        internal static string UpdateOptionalDescription {
            get {
                return ResourceManager.GetString("UpdateOptionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional update available ({0} -&gt; {1}).
        /// </summary>
        internal static string UpdateOptionalTitle {
            get {
                return ResourceManager.GetString("UpdateOptionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is required to continue using TranslateFGO. Please download and install it from our GitHub or website..
        /// </summary>
        internal static string UpdateRequiredDescription {
            get {
                return ResourceManager.GetString("UpdateRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now.
        /// </summary>
        internal static string UpdateRequiredDownload {
            get {
                return ResourceManager.GetString("UpdateRequiredDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required ({0} -&gt; {1}).
        /// </summary>
        internal static string UpdateRequiredTitle {
            get {
                return ResourceManager.GetString("UpdateRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        internal static string UpdateSkip {
            get {
                return ResourceManager.GetString("UpdateSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/rayshift/translatefgo/releases.
        /// </summary>
        internal static string UpdateURL {
            get {
                return ResourceManager.GetString("UpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred with the translation server. Please try again later..
        /// </summary>
        internal static string VersionErrorMessage {
            get {
                return ResourceManager.GetString("VersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string VersionErrorTitle {
            get {
                return ResourceManager.GetString("VersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string VersionExitButton {
            get {
                return ResourceManager.GetString("VersionExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string VersionRetryButton {
            get {
                return ResourceManager.GetString("VersionRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
